Repository BlackSound1/COMP472_A1, pull requests merged in 2021-02, with the labels that each got.

#5 simplified main.py
  src/main.py
  src/utils.py
Labels: enhancement

#7 Added base DT + Generate output
  .gitignore
  src/main.py
  src/utils.py
Labels: enhancement

#9 some small bar chart changes
  src/main.py
Labels: enhancement, fixes issue

#10 remove type annotation
  src/utils.py
Labels: fixes issue

#8 added function to sanitize text
  src/utils.py
Labels: enhancement

#11 Add bestDT + add random state to both DTs + fix utils
  src/main.py
  src/utils.py
Labels: enhancement

#12 Alpha analysis
  .gitignore
  output/BaseDT-all_sentiment_shuffled.txt
  output/BestDT-all_sentiment_shuffled.txt
  output/NaiveBayes-all_sentiment_shuffled.txt
  output/ccp score vs accuracy.png
  src/main.py
  src/utils.py
Labels: enhancement

#13 Add test label distribution + save label distributions as image
  src/main.py
  src/utils.py
Labels: enhancement

#14 Task 4 - Generate wrong predictions file + fix row number
  src/main.py
  src/utils.py
Labels: enhancement

#15 added function to save pics of confusion matrixes
  src/main.py
  src/utils.py
Labels: documentation, enhancement

#16 Add task 4 file
  task-4.txt
Labels: documentation, enhancement

#17 added slideshow and the charts
  output/BaseDT-all_sentiment_shuffled.txt
  output/BestDT-all_sentiment_shuffled.txt
  output/DT-base-confusion-matrix.png
  output/DT-best-confusion-matrix.png
  output/NB-confusion-matrix.png
  output/NaiveBayes-all_sentiment_shuffled-error.txt
  output/NaiveBayes-all_sentiment_shuffled.txt
  output/test_label_distribution.png
  output/training_label_distribution.png
  presentation.pptx
Labels: documentation, enhancement

#18 fix analyze_ccp_alpha
  src/main.py
  src/utils.py
Labels: fixes issue
